stages:
  - build

build-image-job:
  stage: build
  image:
    name: k3s-gcp.cyshall.com/k8s/kaniko-executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"k3s-gcp.cyshall.com/k8s\":{\"auth\":\"$(printf "%s:%s" "admin" "${PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "k3s-gcp.cyshall.com/k8s/iac-module-vpc:latest"
